server:
  port: 8085

spring:
  application:
    name: shop-service
  config:
    import: optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        file-extension: yaml
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/poetry_app?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8mb4&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD:root@123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.poetryapp.shop.entity

logging:
  config: classpath:log4j2.xml
